POST http://localhost:8080/api/score
Content-Type: application/json

{
  "game": "maze",
  "player": "Josephie1",
  "points": 100,
  "playedOn": "2024-04-06T19:33:12"
}
###
GET http://localhost:8080/api/score/maze
###
POST http://localhost:8080/api/rating
Content-Type: application/json

{"game": "maze",
  "player": "mike",
  "rating": 5,
  "ratedOn": "2024-04-06T19:33:12"
}
###
GET http://localhost:8080/api/rating/maze/mikee
###
GET http://localhost:8080/api/rating/maze
###
POST http://localhost:8080/api/comment
Content-Type: application/json

{
  "game": "maze",
  "player": "johnny",
  "comment": "Hello!",
  "commentedOn": "2024-04-06T19:33:12"
}

###
GET http://localhost:8080/api/comment/maze